image: node:12

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint-and-test:
  stage: test
  script:
    - npm install
    - npm add -D esbuild
    - npm test
    - npm lint
    - npm build-all

# Deploy docs to Gitlab pages
pages:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm docs
    - mv docs public
  artifacts:
    paths:
      - public
